server {
    listen 8100;
    server_name localhost;

    location = /pollapp {
        return 301 /pollapp/;
    }

    location /pollapp/ {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /pollapp/index.html;
    }
}
