server {
    listen 8100;
    server_name localhost;

    location = /pollapp-dev {
        return 301 /pollapp-dev/;
    }

    location /pollapp-dev/ {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /pollapp-dev/index.html;
    }
}
