server {
    listen 8100;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location = /pollapp {
        return 301 /pollapp/;
    }

    location /pollapp/branding/ {
        rewrite ^/pollapp/(.*)$ /$1 break;
        try_files $uri =404;
    }

    location /pollapp/ {
        rewrite ^/pollapp/(.*)$ /$1 break;
        try_files $uri $uri/ /index.html;
    }
}
